name: "pagely-deploy"
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to pagely vps
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run composer install
        uses: docker://composer:1.9.1
        with:
          args: install

      - name: Deploy to vps
        uses: pagely/action-deploy@master
        with:
          PAGELY_INTEGRATION_SECRET: ${{ secrets.PAGELY_TOKEN }}
          PAGELY_INTEGRATION_ID: ${{ secrets.PAGELY_INTEGRATION_ID }}
          PAGELY_APP_ID: ${{ secrets.PAGELY_APP_ID }}
          PAGELY_DEPLOY_DEST: /app
